# Generated by Django 2.1.2 on 2019-09-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
