# Generated by Django 2.1.2 on 2019-09-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190928_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
