# Generated by Django 2.1.2 on 2019-09-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_last_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='last_edit',
        ),
    ]
